helm:
  parameters:
  - name: tunarr.controllers.tunarr.containers.tunarr.image.repository
    value: ghcr.io/chrisbenincasa/tunarr
    forcestring: true
  - name: tunarr.controllers.tunarr.containers.tunarr.image.tag
    value: 2026.9.1
    forcestring: true
