{{- with $.Values.komodo }}
{{- if .enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: komodo-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-secret-store
  target:
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        core.pub: |
          -----BEGIN PUBLIC KEY-----
          {{ `{{ .public }}` }}
          -----END PUBLIC KEY-----

        core.key: |
          -----BEGIN PRIVATE KEY-----
          {{ `{{ .private }}` }}
          -----END PRIVATE KEY-----

  data:
    - secretKey: public
      remoteRef:
        key: /komodo
        property: public-key
    - secretKey: private
      remoteRef:
        key: /komodo
        property: private-key
{{- end }}
{{- end }}