helm:
  parameters:
    - name: radarr.controllers.main.containers.main.image.repository
      value: lscr.io/linuxserver/radarr
      forcestring: true
    - name: radarr.controllers.main.containers.main.image.tag
      value: 6.2.1.10461-ls307
      forcestring: true
