apiVersion: v2
name: external-dns
version: 0.21.0
dependencies:
  - name: external-dns
    version: 1.21.1
    repository: https://kubernetes-sigs.github.io/external-dns/
    condition: external-dns.enabled
  - name: external-dns
    version: 1.20.0
    repository: https://kubernetes-sigs.github.io/external-dns/
    condition: external-dns.enabled
    alias: external-dns-secondary