helm:
  parameters:
    - name: sonarr.controllers.main.containers.main.image.repository
      value: lscr.io/linuxserver/sonarr
      forcestring: true
    - name: sonarr.controllers.main.containers.main.image.tag
      value: 4.0.19.2979-ls316
      forcestring: true
